/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'customerName' : string,
  'status' : AppointmentStatus,
  'appointmentType' : AppointmentType,
  'notes' : string,
  'customerId' : bigint,
  'dateTime' : bigint,
}
export type AppointmentStatus = { 'Scheduled' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null };
export type AppointmentType = { 'Measurement' : null } |
  { 'Fitting' : null } |
  { 'Delivery' : null } |
  { 'Consultation' : null };
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'measurements' : [] | [Measurements],
  'address' : string,
  'phone' : string,
}
export interface DashboardStats {
  'todayAppointments' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'readyOrders' : bigint,
  'inProductionOrders' : bigint,
  'totalCustomers' : bigint,
  'monthlyRevenue' : number,
  'deliveredOrders' : bigint,
}
export interface FabricInventory {
  'id' : bigint,
  'fabricName' : string,
  'supplier' : string,
  'color' : string,
  'quantityMeters' : number,
  'pricePerMeter' : number,
  'reorderLevel' : number,
}
export type GarmentType = { 'Shirt' : null } |
  { 'Suit' : null } |
  { 'Trouser' : null } |
  { 'Kurti' : null } |
  { 'Other' : null } |
  { 'Blouse' : null };
export interface Invoice {
  'id' : bigint,
  'tax' : number,
  'customerName' : string,
  'total' : number,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'orderId' : bigint,
  'discount' : number,
  'customerId' : bigint,
  'subtotal' : number,
}
export interface Measurements {
  'hip' : number,
  'chest' : number,
  'neck' : number,
  'trouserLength' : number,
  'sleeveLength' : number,
  'shoulder' : number,
  'shirtLength' : number,
  'waist' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'fabricName' : string,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'deliveryDate' : [] | [bigint],
  'garmentType' : GarmentType,
  'notes' : string,
  'advancePaid' : number,
  'quantity' : bigint,
  'customerId' : bigint,
  'price' : number,
  'fabricColor' : string,
}
export type OrderStatus = { 'InProduction' : null } |
  { 'Delivered' : null } |
  { 'Ready' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type PaymentStatus = { 'PartiallyPaid' : null } |
  { 'Paid' : null } |
  { 'Unpaid' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Staff {
  'id' : bigint,
  'staffId' : string,
  'joinDate' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'role' : StaffRole,
  'email' : string,
  'address' : string,
  'phone' : string,
  'department' : string,
}
export type StaffRole = { 'Helper' : null } |
  { 'Cutter' : null } |
  { 'Receptionist' : null } |
  { 'Tailor' : null } |
  { 'Other' : null } |
  { 'Manager' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppointment' : ActorMethod<
    [bigint, string, bigint, AppointmentType, string],
    Appointment
  >,
  'addCustomer' : ActorMethod<
    [string, string, string, string, [] | [Measurements]],
    Customer
  >,
  'addCustomerPhoto' : ActorMethod<[bigint, string], boolean>,
  'addInventoryItem' : ActorMethod<
    [string, string, number, number, string, number],
    FabricInventory
  >,
  'addOrder' : ActorMethod<
    [
      bigint,
      string,
      GarmentType,
      string,
      string,
      bigint,
      number,
      number,
      bigint,
      string,
    ],
    Order
  >,
  'addStaff' : ActorMethod<
    [string, StaffRole, string, string, string, bigint, string],
    Staff
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInvoice' : ActorMethod<
    [bigint, bigint, string, number, number, number, number, string],
    Invoice
  >,
  'deleteAppointment' : ActorMethod<[bigint], boolean>,
  'deleteCustomer' : ActorMethod<[bigint], boolean>,
  'deleteCustomerPhoto' : ActorMethod<[bigint, string], boolean>,
  'deleteInventoryItem' : ActorMethod<[bigint], boolean>,
  'deleteOrder' : ActorMethod<[bigint], boolean>,
  'deleteStaff' : ActorMethod<[bigint], boolean>,
  'deleteStaffCredentials' : ActorMethod<[string], undefined>,
  'filterCustomersByName' : ActorMethod<[string], Array<Customer>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerPhotos' : ActorMethod<[bigint], Array<string>>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInventory' : ActorMethod<[], Array<FabricInventory>>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByCustomer' : ActorMethod<[bigint], Array<Order>>,
  'getOwnerPassword' : ActorMethod<[], string>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStripeConfiguration' : ActorMethod<[], [] | [StripeConfiguration]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'hasStaffPassword' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'seedData' : ActorMethod<[], undefined>,
  'setOwnerPassword' : ActorMethod<[string], boolean>,
  'setStaffPassword' : ActorMethod<[string, string], boolean>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointmentStatus' : ActorMethod<[bigint, AppointmentStatus], boolean>,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string, [] | [Measurements]],
    boolean
  >,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, string, number, number, string, number],
    boolean
  >,
  'updateInvoicePayment' : ActorMethod<[bigint, PaymentStatus], boolean>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateStaff' : ActorMethod<
    [bigint, string, StaffRole, string, string, string, bigint, string],
    boolean
  >,
  'verifyStaffPassword' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];