/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AppointmentType = IDL.Variant({
  'Measurement' : IDL.Null,
  'Fitting' : IDL.Null,
  'Delivery' : IDL.Null,
  'Consultation' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'Scheduled' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'appointmentType' : AppointmentType,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
  'dateTime' : IDL.Int,
});
export const Measurements = IDL.Record({
  'hip' : IDL.Float64,
  'chest' : IDL.Float64,
  'neck' : IDL.Float64,
  'trouserLength' : IDL.Float64,
  'sleeveLength' : IDL.Float64,
  'shoulder' : IDL.Float64,
  'shirtLength' : IDL.Float64,
  'waist' : IDL.Float64,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'measurements' : IDL.Opt(Measurements),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const FabricInventory = IDL.Record({
  'id' : IDL.Nat,
  'fabricName' : IDL.Text,
  'supplier' : IDL.Text,
  'color' : IDL.Text,
  'quantityMeters' : IDL.Float64,
  'pricePerMeter' : IDL.Float64,
  'reorderLevel' : IDL.Float64,
});
export const GarmentType = IDL.Variant({
  'Shirt' : IDL.Null,
  'Suit' : IDL.Null,
  'Trouser' : IDL.Null,
  'Kurti' : IDL.Null,
  'Other' : IDL.Null,
  'Blouse' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'InProduction' : IDL.Null,
  'Delivered' : IDL.Null,
  'Ready' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'fabricName' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'deliveryDate' : IDL.Opt(IDL.Int),
  'garmentType' : GarmentType,
  'notes' : IDL.Text,
  'advancePaid' : IDL.Float64,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'price' : IDL.Float64,
  'fabricColor' : IDL.Text,
});
export const StaffRole = IDL.Variant({
  'Helper' : IDL.Null,
  'Cutter' : IDL.Null,
  'Receptionist' : IDL.Null,
  'Tailor' : IDL.Null,
  'Other' : IDL.Null,
  'Manager' : IDL.Null,
});
export const Staff = IDL.Record({
  'id' : IDL.Nat,
  'staffId' : IDL.Text,
  'joinDate' : IDL.Int,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : StaffRole,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'PartiallyPaid' : IDL.Null,
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Float64,
  'customerName' : IDL.Text,
  'total' : IDL.Float64,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Nat,
  'discount' : IDL.Float64,
  'customerId' : IDL.Nat,
  'subtotal' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'todayAppointments' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'readyOrders' : IDL.Nat,
  'inProductionOrders' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
  'monthlyRevenue' : IDL.Float64,
  'deliveredOrders' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int, AppointmentType, IDL.Text],
      [Appointment],
      [],
    ),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Measurements)],
      [Customer],
      [],
    ),
  'addCustomerPhoto' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'addInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Float64],
      [FabricInventory],
      [],
    ),
  'addOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        GarmentType,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Int,
        IDL.Text,
      ],
      [Order],
      [],
    ),
  'addStaff' : IDL.Func(
      [IDL.Text, StaffRole, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [Staff],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInvoice' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [Invoice],
      [],
    ),
  'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCustomerPhoto' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStaff' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStaffCredentials' : IDL.Func([IDL.Text], [], []),
  'filterCustomersByName' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInventory' : IDL.Func([], [IDL.Vec(FabricInventory)], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getOwnerPassword' : IDL.Func([], [IDL.Text], ['query']),
  'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getStripeConfiguration' : IDL.Func(
      [],
      [IDL.Opt(StripeConfiguration)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'hasStaffPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'seedData' : IDL.Func([], [], []),
  'setOwnerPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setStaffPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, AppointmentStatus],
      [IDL.Bool],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Measurements)],
      [IDL.Bool],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
      ],
      [IDL.Bool],
      [],
    ),
  'updateInvoicePayment' : IDL.Func([IDL.Nat, PaymentStatus], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
  'updateStaff' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        StaffRole,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'verifyStaffPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AppointmentType = IDL.Variant({
    'Measurement' : IDL.Null,
    'Fitting' : IDL.Null,
    'Delivery' : IDL.Null,
    'Consultation' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'Scheduled' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'appointmentType' : AppointmentType,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
    'dateTime' : IDL.Int,
  });
  const Measurements = IDL.Record({
    'hip' : IDL.Float64,
    'chest' : IDL.Float64,
    'neck' : IDL.Float64,
    'trouserLength' : IDL.Float64,
    'sleeveLength' : IDL.Float64,
    'shoulder' : IDL.Float64,
    'shirtLength' : IDL.Float64,
    'waist' : IDL.Float64,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'measurements' : IDL.Opt(Measurements),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FabricInventory = IDL.Record({
    'id' : IDL.Nat,
    'fabricName' : IDL.Text,
    'supplier' : IDL.Text,
    'color' : IDL.Text,
    'quantityMeters' : IDL.Float64,
    'pricePerMeter' : IDL.Float64,
    'reorderLevel' : IDL.Float64,
  });
  const GarmentType = IDL.Variant({
    'Shirt' : IDL.Null,
    'Suit' : IDL.Null,
    'Trouser' : IDL.Null,
    'Kurti' : IDL.Null,
    'Other' : IDL.Null,
    'Blouse' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'InProduction' : IDL.Null,
    'Delivered' : IDL.Null,
    'Ready' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'fabricName' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'deliveryDate' : IDL.Opt(IDL.Int),
    'garmentType' : GarmentType,
    'notes' : IDL.Text,
    'advancePaid' : IDL.Float64,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'price' : IDL.Float64,
    'fabricColor' : IDL.Text,
  });
  const StaffRole = IDL.Variant({
    'Helper' : IDL.Null,
    'Cutter' : IDL.Null,
    'Receptionist' : IDL.Null,
    'Tailor' : IDL.Null,
    'Other' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const Staff = IDL.Record({
    'id' : IDL.Nat,
    'staffId' : IDL.Text,
    'joinDate' : IDL.Int,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : StaffRole,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'PartiallyPaid' : IDL.Null,
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Float64,
    'customerName' : IDL.Text,
    'total' : IDL.Float64,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Nat,
    'discount' : IDL.Float64,
    'customerId' : IDL.Nat,
    'subtotal' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'todayAppointments' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'readyOrders' : IDL.Nat,
    'inProductionOrders' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
    'monthlyRevenue' : IDL.Float64,
    'deliveredOrders' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, AppointmentType, IDL.Text],
        [Appointment],
        [],
      ),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Measurements)],
        [Customer],
        [],
      ),
    'addCustomerPhoto' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Float64],
        [FabricInventory],
        [],
      ),
    'addOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          GarmentType,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Int,
          IDL.Text,
        ],
        [Order],
        [],
      ),
    'addStaff' : IDL.Func(
        [IDL.Text, StaffRole, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [Staff],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInvoice' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [Invoice],
        [],
      ),
    'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCustomerPhoto' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStaff' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStaffCredentials' : IDL.Func([IDL.Text], [], []),
    'filterCustomersByName' : IDL.Func([IDL.Text], [IDL.Vec(Customer)], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInventory' : IDL.Func([], [IDL.Vec(FabricInventory)], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getOwnerPassword' : IDL.Func([], [IDL.Text], ['query']),
    'getStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getStripeConfiguration' : IDL.Func(
        [],
        [IDL.Opt(StripeConfiguration)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'hasStaffPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'seedData' : IDL.Func([], [], []),
    'setOwnerPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setStaffPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, AppointmentStatus],
        [IDL.Bool],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Measurements),
        ],
        [IDL.Bool],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
        ],
        [IDL.Bool],
        [],
      ),
    'updateInvoicePayment' : IDL.Func([IDL.Nat, PaymentStatus], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Bool], []),
    'updateStaff' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          StaffRole,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'verifyStaffPassword' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };